2020/x/wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path('', views.index, name='index'),
    path('wiki/<str:title>', views.wiki, name='wiki'),
    path('search', views.search, name='search'),
    path('new_entry', views.new_entry, name='new_entry'),
    path('random_entry', views.random_entry, name='random_entry'),
    path('edit', views.edit, name='edit')
]

2020/x/wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

2020/x/wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

2020/x/wiki/encyclopedia/views.py
from django.http.response import HttpResponse
from django.shortcuts import render
from random import randrange

from . import util
import markdown2

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def wiki(request, title):
    entries = util.list_entries()
    if title in entries:
        return render(request, "encyclopedia/wiki.html", 
        {"text": markdown2.markdown(util.get_entry(title)), "title": title})
    else:
        return render(request, "encyclopedia/wiki.html", {"text": None, "title": title})

def search(request):
    entries = util.list_entries()
    term = request.POST["term"]
    if term in entries:
        return render(request, "encyclopedia/wiki.html", 
        {"text": markdown2.markdown(util.get_entry(term)), "title": term})
    search_list = []
    for item in entries:
        if term.lower() in item.lower():
            search_list.append(item)
    if search_list:
        return render(request, "encyclopedia/results.html", {"entries": search_list})
    else:
        return render(request, "encyclopedia/wiki.html", {"text": None, "title": term})

def new_entry(request):
    if request.method == "GET":
        return render(request, "encyclopedia/new.html")
    else:
        title = request.POST["new_title"]
        content = request.POST["new_content"]
        if title in util.list_entries():
            return render(request, "encyclopedia/existing.html", {"title": title})
        else:
            util.save_entry(title, content)
            return wiki(request, title)

def random_entry(request):
    entries = util.list_entries()
    num = len(entries)
    entry = randrange(num)
    title = entries[entry]
    return wiki(request, title)

def edit(request):
    if request.method == "GET":
        title = request.GET["title"]
        content = util.get_entry(title)
        return render(request, 'encyclopedia/edit.html', {"content": content, "title": title})
    else:
        title = request.POST["title"]
        text = request.POST["new_content"]
        util.save_entry(title, text)
        return wiki(request, title)

2020/x/wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit: {{ title }}
{% endblock %}

{% block body %}
<h1>Edit the Entry</h1>
<p>Edit your entry, then click Save to save your changes.</p>
<form action="{% url 'encyclopedia:edit' %}" method="POST">
    {% csrf_token %}
    <b><label for="title">Entry:</label></b>
    <input type="text" id="title" name="title" value="{{ title }}" readonly> .md<br>
    <b><label for="content">Definition:</label></b> (Include the title of the entry 
    in the definition)
    <div class="form-outline w-50 mb-4">
    <textarea class="form-control" id="content" name="new_content" 
    rows="5">{{ content }}</textarea></div>
    Click Save to save your changes and see the revised entry.<br><br>
    <input type="submit" value="Save">
</form>
{% endblock %}

2020/x/wiki/encyclopedia/templates/encyclopedia/existing.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Entry: {{ title }}
{% endblock %}

{% block body %}
<h1>Not Saved: {{ title }}</h1>
<div>
    This entry already exists.  You can read and edit it
    by clicking <a href="wiki/{{ title }}">here</a>.
</div>
{% endblock %}

2020/x/wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li>{{ entry }}</li>
        {% endfor %}
    </ul>

{% endblock %}

2020/x/wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="post">
                    {% csrf_token %}
                    <input class="search" id="term" type="text" name="term" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:new_entry' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random_entry' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

2020/x/wiki/encyclopedia/templates/encyclopedia/new.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    New
{% endblock %}

{% block body %}
    <h1>Add a New Entry</h1>
    <p>Use Markdown to format the text for a new entry.</p>
    <form action="{% url 'encyclopedia:new_entry' %}" method="POST">
        {% csrf_token %}
        <b><label for="new_title">Entry:</label></b>
        <input type="text" id="new_title" name="new_title"> .md<br>
        <b><label for="new_content">Definition:</label></b> (Include the title of the entry 
        in the definition)<br>
        <div class="form-outline w-50 mb-4">
        <textarea class="form-control" id="new_content" name="new_content" rows="5"></textarea>
        </div>
        Click Save to save the entry or Reset
        to clear the form.<br><br>
        <input type="submit" value="Save"> <input type="reset" value="Reset">
    </form>

{% endblock %}

2020/x/wiki/encyclopedia/templates/encyclopedia/results.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search
{% endblock %}

{% block body %}
    <h1>Search Results</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="wiki/{{ entry }}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

2020/x/wiki/encyclopedia/templates/encyclopedia/wiki.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Wiki: {{ title }}
{% endblock %}

{% block body %}
{% if text %}
{{ text | safe }}
<br>
<form action="{% url 'encyclopedia:edit' %}" method="GET">
    <input value="{{ title }}" name="title" type="hidden">
    <input type="submit" value="Edit">
</form>
{% else %}
    <h1>{{ title }}: No such entry.</h1>
    <div>
        To add an entry, <a href="{% url 'encyclopedia:new_entry' %}">click here</a>.
    </div>
{% endif %}
{% endblock %}